logging:
  level:
    ROOT: INFO

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


spring:
  rabbitmq:
    addresses: rabbitmq-service-pro:5672
    username: user
    password: KcqaZOeeZf
    listener:
      simple:
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5 #最大重试次数
          initial-interval: 5000ms #重试间隔时间（单位毫秒）
          max-interval: 1200000ms #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器


sdk:
  data:
    consumer:
      queueName: fat.queue.sdk.data.write.req